### ISSUE TITLE
MBR partitions expansion not working on OSX

### ISSUE THREAD

**Issue by elcritch** [fhunleth/fwup#100]
The new `expand=true` option doesn't work after updating the fwup.conf for `nerves_system_rpi3`. After burning a firmware to a new SD card results in a last partition size set to config value. 

Related to issue #98.

Build Machine: MacOS Sierra 10.12.6 
Fwup Version: 1.3.0 (built with homebrew)

[fwup.conf.txt](https://github.com/fhunleth/fwup/files/2929041/fwup.conf.txt)

**Comment by fhunleth** [comment]
I was able to reproduce the issue with Mojave. I had a note about this root cause that I made when I was using Sierra or High Sierra, so I'm optimistic that the fwup v1.3.1 release will fix the issue for you.
