### ISSUE TITLE
metadata tests failing

### ISSUE THREAD

**Issue by liberza** [fhunleth/fwup#113]
Hi! I was trying to update the Arch packages [fwup](https://aur.archlinux.org/packages/fwup/) and [fwup-git](https://aur.archlinux.org/packages/fwup-git/) today, but I'm getting similar failing tests for both. I haven't gotten around to updating these packages in a while, so perhaps they're missing a new dependency? test-suite.log files are below for both. Please let me know if you need any other info.

[test-suite-1.4.0.log](https://github.com/fhunleth/fwup/files/3854600/test-suite-1.4.0.log)
[test-suite-master.log](https://github.com/fhunleth/fwup/files/3854601/test-suite-master.log)

**Comment by fhunleth** [comment]
Thanks for the heads up. Let me check...

**Comment by fhunleth** [comment]
Cool, Arch is doing reproducible builds. Let me fix those tests.

**Comment by fhunleth** [comment]
Thanks! I was able to reproduce and I fixed it in #114.

Assuming CI is happy and nothing else fails, I plan on making a v1.5.0 release tonight or tomorrow.

**Comment by liberza** [comment]
Nice, thank you for the quick fix!
