### ISSUE TITLE
boot=true flag fails for gpt

### ISSUE THREAD

**Issue by mcarlin-ds** [fhunleth/fwup#132]
When writing a gpt partition with the "boot=true" flag the build fails with the error:
.../images/fwup.conf:162: no such option 'boot'

replacing "boot=true" with "flags=0x4" works properly.   Attached is the fwup.conf (renamed to fwup.conf.txt for upload) 
that works, with the "boot=true" commented out.

[fwup.conf.txt](https://github.com/fhunleth/fwup/files/4547251/fwup.conf.txt)

Thanks!

**Comment by fhunleth** [comment]
I'm glad to hear that 0x4 is the right number for `boot=true`. This seems like an easy add. I'm currently working on some other features in fwup, so I might be able to get it in quickly. Thanks!
