### ISSUE TITLE
Port to Windows

### ISSUE THREAD

**Issue by fhunleth** [fhunleth/fwup#15]
It should be possible to program SDCards from Windows.

**Comment by GregMefford** [comment]
Most of the tests are passing now under Wine using the `windows` branch (see PR #36).
I am beginning to test actual writing of SD cards on a real Windows machine.

**Comment by GregMefford** [comment]
With the merging of #37 to the `windows` branch,, we have a working version of fwup on Windows. All of the features haven't been thoroughly tested yet, but the basic process of burning an SD card is working.

We should shortly have a process in place to package the executable as an MSI for easy installation on Windows. :rocket:

**Comment by fhunleth** [comment]
Windows support is now in v0.9.0!
