### ISSUE TITLE
fwup --help issue

### ISSUE THREAD

**Issue by ypearson** [fhunleth/fwup#4]
/fwup$ fwup --help
Segmentation fault (core dumped)

Running on Virtual Box, Ubuntu 14.04

**Comment by fhunleth-lkc** [comment]
Well, that's embarrassing... I can't say that I run --help that much, and it's not in the unit tests. I'll check it out after I get back. Thank you very much for sending the report.

**Comment by ypearson** [comment]
No problem it happens.

I'm looking forward to using fwup on my projects!

**Comment by fhunleth** [comment]
Amazingly, running "--help" does not produce a segfault on my system. However, I think I found an issue. Could you update to the latest in master and see if it fixes it?

**Comment by ypearson** [comment]
That fixed it! No more seg fault.

**Comment by fhunleth** [comment]
Great! Thanks again for letting me know.
