### ISSUE TITLE
fwup not yet in Chocolatey's repo

### ISSUE THREAD

**Issue by gallexme** [fhunleth/fwup#49]
fwup not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

**Comment by fhunleth** [comment]
Soon, I hope:

https://chocolatey.org/packages/fwup/0.9.1

**Comment by fhunleth** [comment]
It's still not on chocolatey, but look here now:

https://chocolatey.org/packages/fwup/0.9.2

**Comment by fhunleth** [comment]
Just posted now!

https://chocolatey.org/packages/fwup

**Comment by GregMefford** [comment]
🎉 🚀 ✨
